"""empty message

Revision ID: 0d20f57adc67
Revises: ed657e16ce20
Create Date: 2016-10-25 00:21:27.423206

"""

# revision identifiers, used by Alembic.
revision = '0d20f57adc67'
down_revision = 'ed657e16ce20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('aboutme', sa.String(length=255), nullable=True))
    op.add_column(u'user', sa.Column('nickname', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'nickname')
    op.drop_column(u'user', 'aboutme')
    op.drop_table('post')
    ### end Alembic commands ###
