"""empty message

Revision ID: 67364b1d2f04
Revises: 0d20f57adc67
Create Date: 2016-10-25 00:27:56.405768

"""

# revision identifiers, used by Alembic.
revision = '67364b1d2f04'
down_revision = '0d20f57adc67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
