"""empty message

Revision ID: b2b7b8c6e096
Revises: fbbe04b71eab
Create Date: 2016-11-01 09:15:03.450434

"""

# revision identifiers, used by Alembic.
revision = 'b2b7b8c6e096'
down_revision = 'fbbe04b71eab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('followerid', sa.Integer(), nullable=True),
    sa.Column('followedid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followedid'], ['user.id'], ),
    sa.ForeignKeyConstraint(['followerid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'post_ibfk_1', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['userid'], ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(u'post_ibfk_1', 'post', 'user', ['userid'], ['id'])
    op.drop_table('follow')
    ### end Alembic commands ###
